name: first-workflow
on: [push,pull]
env:
  MONGO_DB_NAME: db-demo
  MONGO_DB_PASSWORD: ${{ secrets.MONGO_DB_PASSWORD }}
jobs:
  first-job:
    environment: testing
    env:
      MONGO_DB_NAME: db-demo-test # this will override the value
      PORT: 8080
    runs-on: ubuntu-latest
    steps:
      - name: Print Greeting
        run: echo "Hello World!"
      - name: last job
        run: echo "Done Job bye!"
      - name: Get Code
        uses: actions/checkout@v6.0.2
      - name: Install Nodejs
        uses: actions/setup-node@v6.2.0
        with:
          node-version: 18
      - name: check the repo
        run: ls -l
      - name: check the node version
        run: node --version
      - name: Run server
        run: npm start & npx wait-on http://127.0.0.1:$PORT
      - name: Output Information
        run: | 
          echo "MONGO_DB_NAME: ${{ env.MONGO_DB_NAME }}"
  build:
    runs-on: ubuntu-latest
    outputs:
      script-file: ${{ steps.publish.outputs.script-file }}
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Caching dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}
      - name: install Dependencies
        run: npm ci
      - name: Build Website
        run: npm run build
      - name: Publish JS filename
        id: publish
        run: find dist/assets/*.js -type f -execdir echo 'script-file={}' >> $GITHUB_OUTPUT ';'
      - name: Upload artificats
        uses: actions/upload-artifact@v3
        with:
          name: dist-files
          path: dist
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Caching dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}
      - name: install Dependencies
        run: npm ci
      - name: Get build artifact
        uses: actions/download-artifact@v3
        with:
          name: dist-files
      - name: output-filename
        run: echo "${{ needs.build.outputs.script-file }}"
